### ISSUE TITLE
Some `Qchem` tests are failing due to new release of `H5Py` 3.3.0 which is used in `PyScf`

### ISSUE THREAD

**Issue by rmoyard** [PennyLaneAI/pennylane#1429]
#### Issue description

Some `Qchem` tests are not passing due to the new release of `H5Py` 3.3.0 which is used in `PyScf`. The quick fix is to use an older version of `H5Py` when installing dependencies in the test environment until `PyScf` has introduced a fix.

#### Source code and tracebacks
A failed test example:

```
____________________ test_finit_diff_hamilt[0-coeffs0-ops0] ____________________
Traceback (most recent call last):
  File "/home/runner/work/pennylane/pennylane/qchem/tests/test_deriv_hamilt.py", line 182, in test_finit_diff_hamilt
    deriv = qml.finite_diff(hamilt, N=1, argnum=0, idx=[i])(x)
  File "/usr/share/miniconda/lib/python3.7/site-packages/pennylane/_grad.py", line 229, in _fd_first_order_centered
    f(*args[:argnum], x + shift, *args[argnum + 1 :], **kwargs)
  File "/home/runner/work/pennylane/pennylane/qchem/tests/test_deriv_hamilt.py", line 175, in hamilt
    ["H", "O", "H"], x, active_electrons=2, active_orbitals=2, outpath=tmpdir.strpath
  File "/home/runner/work/pennylane/pennylane/qchem/pennylane_qchem/qchem/structure.py", line 831, in molecular_hamiltonian
    hf_file = meanfield(symbols, coordinates, name, charge, mult, basis, package, outpath)
  File "/home/runner/work/pennylane/pennylane/qchem/pennylane_qchem/qchem/structure.py", line 335, in meanfield
    from openfermionpyscf import run_pyscf
  File "/usr/share/miniconda/lib/python3.7/site-packages/openfermionpyscf/__init__.py", line 17, in <module>
    from ._pyscf_molecular_data import PyscfMolecularData
  File "/usr/share/miniconda/lib/python3.7/site-packages/openfermionpyscf/_pyscf_molecular_data.py", line 17, in <module>
    from pyscf import ao2mo
  File "/usr/share/miniconda/lib/python3.7/site-packages/pyscf/__init__.py", line 71, in <module>
    from pyscf import lib
  File "/usr/share/miniconda/lib/python3.7/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/usr/share/miniconda/lib/python3.7/site-packages/pyscf/lib/numpy_helper.py", line 27, in <module>
    from pyscf.lib import misc
  File "/usr/share/miniconda/lib/python3.7/site-packages/pyscf/lib/misc.py", line 46, in <module>
    h5py.get_config().default_file_mode = 'a'
  File "h5py/h5.pyx", line 179, in h5py.h5.H5PYConfig.default_file_mode.__set__
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead.
```

**Comment by josh146** [comment]
@rmoyard in the meantime has PySCF released an update to support h5py 3.3?

**Comment by licedric** [comment]
Apparently fixed in https://github.com/pyscf/pyscf/issues/1016 but still only in Alpha.

**Comment by dime10** [comment]
PySCF 2.0 has since been released, but it seems we can't use it yet (see https://github.com/PennyLaneAI/pennylane/pull/1827).

Since the bug itself has been fixed, this issue can be closed. I will open a new issue about adding support for PySCF 2.0 and H5Py 3.3.0.
