### ISSUE TITLE
QNGoptimizer with reused parameters

### ISSUE THREAD

**Issue by JoeGibbs88** [PennyLaneAI/pennylane#1759]
I would like to use the QNGoptimizer to train an ansatz that uses the same parameter as an input to multiple rotation gates. Here is an example.

```
import numpy as np
import pennylane as qml

dev = qml.device("default.qubit", wires=2)
@qml.qnode(dev)
def circuit(params):
    
    qml.RY(params[0], wires=0)
    #qml.RY(params[0], wires=1)

    return qml.expval(qml.PauliZ(0))

steps = 200
qng_cost = []
opt = qml.QNGOptimizer(0.01)

theta = np.array([1.0])
for _ in range(steps):
    theta = opt.step(circuit, theta)
    qng_cost.append(circuit(theta))
```

The code above runs fine, however, if the second line in circuit() is uncommented, I get the error:

```
Traceback (most recent call last):
  File "example.py", line 160, in <module>
    theta = opt.step(circuit, theta)
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/pennylane/optimize/qng.py", line 242, in step
    **kwargs,
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/pennylane/optimize/qng.py", line 201, in step_and_cost
    new_args = self.apply_grad(g, args)
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/pennylane/optimize/qng.py", line 260, in apply_grad
    x_new_flat = x_flat - self.stepsize * np.linalg.solve(self.metric_tensor, grad_flat)
  File "<__array_function__ internals>", line 6, in solve
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 393, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 1 is different from 2)
```

Is there a method I am unaware of that allows the QNGoptimizer to be applied to ansatzes with shared parameters, or is this incompatible in its common form?

**Comment by josh146** [comment]
@JoeGibbs88 let me know if the development PL version works for you, or if you have any other questions. In the meantime, I will close this issue, since the underlying issue is already solved in the codebase

**Comment by JoeGibbs88** [comment]
Your solution also worked for me, thanks for the help :)
