### ISSUE TITLE
[BUG] Import error with pennylane 0.19.1

### ISSUE THREAD

**Issue by DarthMalloc** [PennyLaneAI/pennylane#1941]
### Expected behavior

When I run the line 

'import pennylane as qml'

there should be no output in IDLE.

### Actual behavior

Running this line results in an AttributeError.

### Source code

```shell
import pennylane as qml
```

### Tracebacks

```shell
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pennylane as qml
  File "/usr/local/lib/python3.8/dist-packages/pennylane/__init__.py", line 29, in <module>
    import pennylane.kernels
  File "/usr/local/lib/python3.8/dist-packages/pennylane/kernels/__init__.py", line 18, in <module>
    from .cost_functions import (
  File "/usr/local/lib/python3.8/dist-packages/pennylane/kernels/cost_functions.py", line 19, in <module>
    from ..math import frobenius_inner_product
  File "/usr/local/lib/python3.8/dist-packages/pennylane/math/__init__.py", line 36, in <module>
    from .multi_dispatch import (
  File "/usr/local/lib/python3.8/dist-packages/pennylane/math/multi_dispatch.py", line 22, in <module>
    from . import single_dispatch  # pylint:disable=unused-import
  File "/usr/local/lib/python3.8/dist-packages/pennylane/math/single_dispatch.py", line 64, in <module>
    ar.autoray._BACKEND_ALIASES["pennylane"] = "autograd"
AttributeError: module 'autoray.autoray' has no attribute '_BACKEND_ALIASES'
```

### System information

```shell
Could not be posted, since error occurred at import.
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Hi @DarthMalloc, thank you for the report! :slightly_smiling_face: Which version of `autoray` are you using (or potentially could it be that it's not installed)?

**Comment by antalszava** [comment]
It seems that the issue is with `autoray` `<v0.2.5`.

**Comment by josh146** [comment]
@DarthMalloc could you try upgrading your version of autoray? For example,

```
pip install autoray --upgrade
```
