### ISSUE TITLE
[BUG] Device gradient no longer called despite diff_method='device'

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2146]
### Expected behavior

Expected behavior is that an exception is thrown in the code below.

### Actual behavior

Actual behavior on master (commit b820a14369ad7785fb12577ba05cf6e54806691e) is that the exception is not thrown, which shows that the device gradient is not called.

### Additional information

My feeling is that this may be caused by PennyLane swapping out my device for some other qubit device. @josh146 knows the backfgroud.

### Source code

```shell
import pennylane as qml
    from pennylane.devices import DefaultQubit

    class MyDev(DefaultQubit):
        @classmethod
        def capabilities(cls):
            capabilities = super().capabilities().copy()
            capabilities.update(
                provides_jacobian=True,
            )
            return capabilities

        def jacobian(self, operations_or_tape, observables=None, parameters=None):
            raise Exception("This exception signals that the device jacobian() was called")

    @qml.qnode(MyDev(wires=2), diff_method='device')
    def circuit(params):
        return qml.expval(qml.Hermitian(np.array([[1, 0], [0, 0]]), wires=0))

    params = np.array([0.75916255, -2.16921113])

    with pytest.raises(Exception, match=r"This exception signals that the device jacobian.* was called") as excinfo:
        qml.jacobian(circuit)(params)
```

### System information

```shell
See above for information on which PL version was used.
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment]
Hi @cvjjm, this is super odd, but if I run the above code, I get the exception, as expected:

```python
import pennylane as qml
from pennylane.devices import DefaultQubit
from pennylane import numpy as np

class MyDev(DefaultQubit):
    @classmethod
    def capabilities(cls):
        capabilities = super().capabilities().copy()
        capabilities.update(
            provides_jacobian=True,
        )
        return capabilities

    def jacobian(self, operations_or_tape, observables=None, parameters=None):
        raise Exception("This exception signals that the device jacobian() was called")

@qml.qnode(MyDev(wires=2), diff_method='device')
def circuit(params):
    return qml.expval(qml.Hermitian(np.array([[1, 0], [0, 0]]), wires=0))

params = np.array([0.75916255, -2.16921113])

jac = qml.jacobian(circuit)(params)

print(jac)
```

The traceback that I get is:

```
Traceback (most recent call last):
  File "test8.py", line 23, in <module>
    jac = qml.jacobian(circuit)(params)
  File "/home/josh/xanadu/pennylane/pennylane/_grad.py", line 309, in _jacobian_function
    jac = tuple(_jacobian(func, arg)(*args, **kwargs) for arg in _argnum)
  File "/home/josh/xanadu/pennylane/pennylane/_grad.py", line 309, in <genexpr>
    jac = tuple(_jacobian(func, arg)(*args, **kwargs) for arg in _argnum)
  File "/home/josh/miniconda3/lib/python3.8/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/home/josh/miniconda3/lib/python3.8/site-packages/autograd/differential_operators.py", line 57, in jacobian
    vjp, ans = _make_vjp(fun, x)
  File "/home/josh/miniconda3/lib/python3.8/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/home/josh/miniconda3/lib/python3.8/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/home/josh/miniconda3/lib/python3.8/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "/home/josh/xanadu/pennylane/pennylane/qnode.py", line 549, in __call__
    res = qml.execute(
  File "/home/josh/xanadu/pennylane/pennylane/interfaces/batch/__init__.py", line 407, in execute
    res = _execute(
  File "/home/josh/xanadu/pennylane/pennylane/interfaces/batch/autograd.py", line 64, in execute
    return _execute(
  File "/home/josh/miniconda3/lib/python3.8/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/home/josh/xanadu/pennylane/pennylane/interfaces/batch/autograd.py", line 108, in _execute
    res, jacs = execute_fn(tapes, **gradient_kwargs)
  File "/home/josh/miniconda3/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/josh/xanadu/pennylane/pennylane/_device.py", line 536, in execute_and_gradients
    jacs.append(gradient_method(circuit, **kwargs))
  File "test8.py", line 15, in jacobian
    raise Exception("This exception signals that the device jacobian() was called")
Exception: This exception signals that the device jacobian() was called
```

**Comment by josh146** [comment]
This is on the most recent version of PL `master` branch, commit 92e572f0cf8a0ba950ddd0e9440abfc1d9943c27

**Comment by josh146** [comment]
I see that the circuit in the above code has no operations, should there be some here?

**Comment by cvjjm** [comment]
It turns out the problem resulted from standard numpy being loaded in the context of the unit test that I showed you earlier and not pennylane.numpy. This was not obvious because of the way the test code was structured. You minimal example does work fine, so this is not a bug in PL, but in our code. Sorry for wasting your time...

**Comment by josh146** [comment]
I can verify that swapping to vanilla numpy results in

```python
>>> qml.jacobian(circuit)(params)
()
```

and now I know the cause of this issue 🙂 We have recently in master stopped automatically casting all QNode inputs to `pennylane.numpy` arrays (see #2116). This 'hotfix' was originally to allow Python floats to remain trainable, but had too many buggy side effects that we determined it was important to remove, and not attempt to cast user-provided QNode arguments.

As a result, if you use vanilla NumPy, autograd sees no trainable parameters, and the output is simply an empty tuple --- the device is never called!

Tagging @antalszava and @dime10 here, as just yesterday we were wondering if we should raise a warning if no trainable parameters are present, to alert that 'something may have gone wrong'.
