### ISSUE TITLE
[BUG] unable to checkpoint model with qml.qnn.TorchLayer

### ISSUE THREAD

**Issue by dominicpasquali** [PennyLaneAI/pennylane#2204]
### Expected behavior

something like:
```
Average loss over epoch 1: 0.4803
Average loss over epoch 2: 0.3553
Accuracy: 78.0%
```

output file is generated by PATH

### Actual behavior

Checkpoint file is created but stops short of including full model.

PyTorch unable to pickle qnode: _pickle.PicklingError: Can't pickle <function qnode at 0x7fc7e4169160>: it's not the same object as __main__.qnode

### Additional information

Error occurs every time.

### Source code

```shell
# Coping and pasting code from: https://pennylane.ai/qml/demos/tutorial_qnn_module_torch.html

import torch
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import make_moons

# Set random seeds
torch.manual_seed(42)
np.random.seed(42)

X, y = make_moons(n_samples=200, noise=0.1)
y_ = torch.unsqueeze(torch.tensor(y), 1)  # used for one-hot encoded labels
y_hot = torch.scatter(torch.zeros((200, 2)), 1, y_, 1)

c = ["#1f77b4" if y_ == 0 else "#ff7f0e" for y_ in y]  # colours for each class
#plt.axis("off")
#plt.scatter(X[:, 0], X[:, 1], c=c)
#plt.show()

import pennylane as qml

n_qubits = 2
dev = qml.device("default.qubit", wires=n_qubits)

@qml.qnode(dev)
def qnode(inputs, weights):
    qml.AngleEmbedding(inputs, wires=range(n_qubits))
    qml.BasicEntanglerLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]

n_layers = 6
weight_shapes = {"weights": (n_layers, n_qubits)}

qlayer = qml.qnn.TorchLayer(qnode, weight_shapes)

clayer_1 = torch.nn.Linear(2, 2)
clayer_2 = torch.nn.Linear(2, 2)
softmax = torch.nn.Softmax(dim=1)
layers = [clayer_1, qlayer, clayer_2, softmax]
model = torch.nn.Sequential(*layers)

opt = torch.optim.SGD(model.parameters(), lr=0.2)
loss = torch.nn.L1Loss()

X = torch.tensor(X, requires_grad=True).float()
y_hot = y_hot.float()

batch_size = 5
batches = 200 // batch_size

data_loader = torch.utils.data.DataLoader(
    list(zip(X, y_hot)), batch_size=5, shuffle=True, drop_last=True
)

epochs = 2

for epoch in range(epochs):

    running_loss = 0

    for xs, ys in data_loader:
        opt.zero_grad()

        loss_evaluated = loss(model(xs), ys)
        loss_evaluated.backward()

        opt.step()

        running_loss += loss_evaluated

    avg_loss = running_loss / batches
    print("Average loss over epoch {}: {:.4f}".format(epoch + 1, avg_loss))

y_pred = model(X)
predictions = torch.argmax(y_pred, axis=1).detach().numpy()

correct = [1 if p == p_true else 0 for p, p_true in zip(predictions, y)]
accuracy = sum(correct) / len(correct)
print(f"Accuracy: {accuracy * 100}%")

# Saving a checkpoint after training

PATH = "./checkpoint.pth"

torch.save({
            'model': model,
            'model_state_dict': model.state_dict(),
            'optimizer': opt,
            'optimizer_state_dict': opt.state_dict(),
            'loss': running_loss,
            }, PATH)
```

### Tracebacks

```shell
Average loss over epoch 1: 0.4943
Average loss over epoch 2: 0.4226
Accuracy: 75.5%
Traceback (most recent call last):
  File "/home/PL_save.py", line 84, in <module>
    torch.save({
  File "/home/miniconda3/envs/py9/lib/python3.9/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/miniconda3/envs/py9/lib/python3.9/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function qnode at 0x7fc7e4169160>: it's not the same object as __main__.qnode
```

### System information

```shell
>>> import pennylane as qml; qml.about()
Name: PennyLane
Version: 0.21.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/miniconda3/envs/py9/lib/python3.9/site-packages
Requires: autoray, retworkx, cachetools, semantic-version, scipy, pennylane-lightning, networkx, numpy, toml, appdirs, autograd
Required-by: PennyLane-Lightning
Platform info:           Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-glibc2.28
Python version:          3.9.7
Numpy version:           1.22.2
Scipy version:           1.8.0
Installed devices:
- default.gaussian (PennyLane-0.21.0)
- default.mixed (PennyLane-0.21.0)
- default.qubit (PennyLane-0.21.0)
- default.qubit.autograd (PennyLane-0.21.0)
- default.qubit.jax (PennyLane-0.21.0)
- default.qubit.tf (PennyLane-0.21.0)
- default.qubit.torch (PennyLane-0.21.0)
- lightning.qubit (PennyLane-Lightning-0.21.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
I have a temporary workaround while I'm working on a better fix.

The problem is that we can't pickle the qnode. This happens because of naming confusion between the QNode and the function that the QNode is wrapping.

If you construct the QNode with `qml.QNode` like:

```python
def qfunc(inputs, weights):
    qml.AngleEmbedding(inputs, wires=range(n_qubits))
    qml.BasicEntanglerLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]

qnode = qml.QNode(qfunc, dev)
```

This would eliminate the naming confusion and create a pickle-able object.

**Comment by dominicpasquali** [comment]
> I have a temporary workaround while I'm working on a better fix.
> 
> The problem is that we can't pickle the qnode. This happens because of naming confusion between the QNode and the function that the QNode is wrapping.
> 
> If you construct the QNode with `qml.QNode` like:
> 
> ```python
> def qfunc(inputs, weights):
>     qml.AngleEmbedding(inputs, wires=range(n_qubits))
>     qml.BasicEntanglerLayers(weights, wires=range(n_qubits))
>     return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]
> 
> qnode = qml.QNode(qfunc, dev)
> ```
> 
> This would eliminate the naming confusion and create a pickle-able object.

@albi3ro - awesome! Thank you for the temporary work around (I'll play around with it soon!) and I can't wait to see your better fix! Thank you!

**Comment by antalszava** [comment]
@dominicpasquali no worries! Good to know that this is useful, we can consider more support here in the future.

**Comment by dominicpasquali** [comment]
Hi @antalszava - could you please reapply the bug :bug: label? The temporary workaround as provided by @albi3ro, while overcoming the pickle problem, doesn't properly import the import the QNode from the pickled file.

As previously mentioned, I applied the following to my code:
```
#@qml.qnode(dev)
#def qnode(inputs, weights):
def qfunc(inputs, weights):
    qml.AngleEmbedding(inputs, wires=range(n_qubits))
    qml.BasicEntanglerLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]

qnode = qml.QNode(qfunc, dev)
```

and this produced the desired output:
```
Average loss over epoch 1: 0.4943
Average loss over epoch 2: 0.4226
Accuracy: 75.5%
```

However if we try to then import the pickle from our saved values via:
```
#n_qubits = 2
#dev = qml.device("default.qubit", wires=n_qubits)

#@qml.qnode(dev)
#def qnode(inputs, weights):
#def qfunc(inputs, weights):
#    qml.AngleEmbedding(inputs, wires=range(n_qubits))
#    qml.BasicEntanglerLayers(weights, wires=range(n_qubits))
#    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]

#qnode = qml.QNode(qfunc, dev)

#n_layers = 6
#weight_shapes = {"weights": (n_layers, n_qubits)}

#qlayer = qml.qnn.TorchLayer(qnode, weight_shapes)

#clayer_1 = torch.nn.Linear(2, 2)
#clayer_2 = torch.nn.Linear(2, 2)
#softmax = torch.nn.Softmax(dim=1)
#layers = [clayer_1, qlayer, clayer_2, softmax]
#model = torch.nn.Sequential(*layers)

# Loading the model
PATH = "./checkpoint.pth"
#defining what we are outputting
checkpoint = torch.load(PATH)
model = checkpoint['model']
model.load_state_dict(checkpoint['model_state_dict'])
opt = checkpoint['optimizer']
opt.load_state_dict(checkpoint['optimizer_state_dict'])
```

we are returned

```
<ipython-input-4-fbf26df8a4bc> in <module>()
     47 PATH = "./checkpoint.pth"
     48 #defining what we are outputting
---> 49 checkpoint = torch.load(PATH)
     50 model = checkpoint['model']
     51 model.load_state_dict(checkpoint['model_state_dict'])

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    605                     opened_file.seek(orig_position)
    606                     return torch.jit.load(opened_file)
--> 607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    609 

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
    880     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
    881     unpickler.persistent_load = persistent_load
--> 882     result = unpickler.load()
    883 
    884     torch._utils._validate_loaded_sparse_tensors()

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in find_class(self, mod_name, name)
    873         def find_class(self, mod_name, name):
    874             mod_name = load_module_mapping.get(mod_name, mod_name)
--> 875             return super().find_class(mod_name, name)
    876 
    877     # Load the data (which may in turn use `persistent_load` to load tensors)

AttributeError: Can't get attribute 'qfunc' on <module '__main__'>
```

this is fixed just by calling ```qfunc```:
```
n_qubits = 2
#dev = qml.device("default.qubit", wires=n_qubits)

#@qml.qnode(dev)
#def qnode(inputs, weights):
def qfunc(inputs, weights):
    qml.AngleEmbedding(inputs, wires=range(n_qubits))
    qml.BasicEntanglerLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]

#qnode = qml.QNode(qfunc, dev)

#n_layers = 6
#weight_shapes = {"weights": (n_layers, n_qubits)}

#qlayer = qml.qnn.TorchLayer(qnode, weight_shapes)

#clayer_1 = torch.nn.Linear(2, 2)
#clayer_2 = torch.nn.Linear(2, 2)
#softmax = torch.nn.Softmax(dim=1)
#layers = [clayer_1, qlayer, clayer_2, softmax]
#model = torch.nn.Sequential(*layers)

# Loading the model
PATH = "./checkpoint.pth"
#defining what we are outputting
checkpoint = torch.load(PATH)
model = checkpoint['model']
model.load_state_dict(checkpoint['model_state_dict'])
opt = checkpoint['optimizer']
opt.load_state_dict(checkpoint['optimizer_state_dict'])
```

which outputs the expected return of:
```
Average loss over epoch 1: 0.2875
Average loss over epoch 2: 0.2138
Accuracy: 84.0%
```

**Comment by isaacdevlugt** [comment]
Hi everyone! I stumbled upon this cool package called `cloudpickle` today: https://github.com/cloudpipe/cloudpickle

If I replace the call to `torch.save` in the posted source code with the following code, I get no errors. 

```
import cloudpickle

dictionary = {
    "model": model,
    "model_state_dict": model.state_dict(),
    "optimizer": opt,
    "optimizer_state_dict": opt.state_dict(),
    "loss": running_loss,
}

with open(PATH, "wb") as f:
    cloudpickle.dump(dictionary, f)
```

Then, one can load back the dictionary with `pickle` as follows.

```
import pickle

with open(PATH, "rb") as f:
    dictionary = pickle.load(f)

print(dictionary)
```

Is this too good to be true?

**Comment by anhphuong-ngo** [comment]
I have the same error, but I put it in the format of "Creating non-sequential models". I appreciate any suggestions to fix it. Thanks!

import pennylane as qml
from pennylane.qnode import QNode

n_qubits = 12
dev = qml.device("default.qubit", wires=n_qubits)
@qml.qnode(dev)
def qnode(inputs, weights):
    qml.AngleEmbedding(inputs, wires=range(n_qubits))
    qml.BasicEntanglerLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]
n_layers = 4
weight_shapes = {"weights": (n_layers, n_qubits)}

class Net(torch.nn.Module):
    def __init__(self, s_dim, a_dim):
        super().__init__()
        self.s_dim = s_dim
        self.a_dim = a_dim
        self.pi1 = nn.Linear(s_dim, 128)
        self.pi2 = nn.Linear(128, a_dim)
        self.qlayer_1 = qml.qnn.TorchLayer(qnode, weight_shapes)
        self.qlayer_2 = qml.qnn.TorchLayer(qnode, weight_shapes)
        self.v1 = nn.Linear(s_dim, 128)
        self.v2 = nn.Linear(128, 1)
    
def forward(self, x):
        x_1 = self.pi1(x)
        x_2 = self.qlayer_1(x_1)
        logits = self.pi2(x_2)
        y_1 = self.v1(x)
        y_2 = self.qlayer_2(y_1)
        values = self.v2(y_2)
        return logits, values

    def choose_action(self, s):
        self.eval()
        logits, _ = self.forward(s)
        prob1 = F.softmax(logits[0][0][:max_charging_rate], dim=-1).data
        prob2 = F.softmax(logits[0][0][max_charging_rate:], dim=-1).data
        m1 = self.distribution(prob1)
        m2=self.distribution(prob2)
        a1=m1.sample().numpy()
        a2=m2.sample().numpy()
        #print(a1)
        #print(a2)
        return np.array([a1,a2])

    def loss_func(self, s, a, v_t):
        self.train()
        logits, values = self.forward(s)
        td = v_t - values
        c_loss = td.pow(2)
        prob1 = F.softmax(logits[:,:max_charging_rate], dim=-1).data
        prob2 = F.softmax(logits[:,max_charging_rate:], dim=-1).data
        m1 = self.distribution(prob1)
        m2=self.distribution(prob2)
        #print(a.shape)
        #print(a[:,0])
        #print(a[:,1])
        exp_v = m1.log_prob(a[:,0])*m2.log_prob(a[:,1])* td.detach().squeeze()
        a_loss = -exp_v
        total_loss = (c_loss + a_loss).mean()
        return total_loss

#-------------------------------------------------------------------------
class Worker(mp.Process):
    def __init__(self, gnet, opt, global_ep, global_ep_r, res_queue, name):
        super(Worker, self).__init__()
        self.name = 'w%02i' % name
        self.g_ep, self.g_ep_r, self.res_queue = global_ep, global_ep_r, res_queue
        self.gnet, self.opt = gnet, opt
        self.lnet = Net(N_S, N_A)           # local network
        self.env = env

    def run(self):
        total_step = 1
        while self.g_ep.value < MAX_EP:
            ################################
            #       Initial State          #
            ################################
            a=np.array([100,0])
            s=torch.tensor([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]).reshape((1,N_S)).unsqueeze(0)
            real_state=np.array([])
            #########################
            buffer_s, buffer_a, buffer_r = [], [], []
            ep_r = 0.
            for t in range(MAX_EP_STEP):
                a = self.lnet.choose_action(s)
                r, real_state_, s_= self.env(a,real_state,t)
                r=np.expand_dims(np.expand_dims(r, 0), 0)
                s_=s_.reshape((1,N_S)).unsqueeze(0).float()
                ep_r += r
                buffer_a.append(np.array(a))
                buffer_s.append(s.squeeze().numpy())
                buffer_r.append(r.squeeze())
                done=False
                if t == MAX_EP_STEP - 1:
                    done = True
                if total_step % UPDATE_GLOBAL_ITER == 0 or done:  # update global and assign to local net
                    # sync
                    push_and_pull(self.opt, self.lnet, self.gnet, done, s_, buffer_s, buffer_a, buffer_r, GAMMA)
                    buffer_s, buffer_a, buffer_r = [], [], []
                    
                    if done:  # done and print information
                        record(self.g_ep, self.g_ep_r, ep_r, self.res_queue, self.name)
                        break
                s = s_
                real_state=real_state_
                total_step += 1
        self.res_queue.put(None)

if __name__ == "__main__":
    gnet = Net(N_S, N_A)        # global network
    gnet.share_memory()         # share the global parameters in multiprocessing
    opt = SharedAdam(gnet.parameters(), lr=1e-4, betas=(0.92, 0.999))      # global optimizer
    global_ep, global_ep_r, res_queue = mp.Value('i', 0), mp.Value('d', 0.), mp.Queue()

    # unparallel training
    # workers = [Worker(gnet, opt, global_ep, global_ep_r, res_queue, i) for i in range(1)]
    # parallel training
    workers = [Worker(gnet, opt, global_ep, global_ep_r, res_queue, i) for i in range(mp.cpu_count())]
    [w.start() for w in workers]
    res = []                    # record episode reward to plot
    while True:
        r = res_queue.get()
        if r is not None:
            res.append(r)
        else:
            break
    [w.join() for w in workers]

    import matplotlib.pyplot as plt
    plt.plot(res)
    plt.ylabel('Moving average ep reward')
    plt.xlabel('Step')
    plt.show()

#--------------------------------------------------------------------------
#Error shows up as:

Traceback (most recent call last):

  File "C:\Users\ango1\Desktop\Quantum Reinforcement Learning\RL_EV_Experiment04_Pennylane\code\HSA.py", line 279, in <module>
    [w.start() for w in workers]

  File "C:\Users\ango1\Desktop\Quantum Reinforcement Learning\RL_EV_Experiment04_Pennylane\code\HSA.py", line 279, in <listcomp>
    [w.start() for w in workers]

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

PicklingError: Can't pickle <function qnode at 0x000001F74DED9430>: it's not the same object as __main__.qnode


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
