### ISSUE TITLE
[BUG] PennyLane v0.22.1 fails tests

### ISSUE THREAD

**Issue by dominicpasquali** [PennyLaneAI/pennylane#2390]
### Expected behavior

I expect PennyLane tagged version to pass test suite with 0 failures and 0 warnings.

### Actual behavior

PennyLane outputs

```
9 failed, 8976 passed, 1600 skipped, 22 xfailed, 4 xpassed, 1377 warnings
```

### Additional information

Issue reproduces always.

### Source code

```shell
cd pennylane
git checkout v0.22.1
make test
```

### Tracebacks

```shell
python3 -m pytest tests --tb=native --no-flaky-report
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.7.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/pennylane/tests, configfile: pytest.ini
plugins: flaky-3.7.0, cov-3.0.0, mock-3.7.0
collected 10584 items / 27 skipped                                                                                                                                                                        
...
[many lines here. abbreviating output]
...
[100%]

================================================================================================ FAILURES =================================================================================================
_______________________________________________________________________ TestCutCircuitTransform.test_simple_cut_circuit[None-True] ________________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 1960, in test_simple_cut_circuit
    assert np.isclose(cut_circuit(x), float(circuit(x)), atol=atol)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
_____________________________________________________________________ TestCutCircuitTransform.test_simple_cut_circuit[10000000-True] ______________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 1960, in test_simple_cut_circuit
    assert np.isclose(cut_circuit(x), float(circuit(x)), atol=atol)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
_____________________________________________________________________ TestCutCircuitTransform.test_with_mid_circuit_measurement[True] _____________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 2090, in test_with_mid_circuit_measurement
    assert np.isclose(cut_circuit(x), float(circuit(x)))
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
_____________________________________________________________________________ TestCutCircuitTransform.test_device_wires[True] _____________________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 2319, in test_device_wires
    res_1 = cut_circuit_1()
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
_________________________________________________________________ TestCutCircuitTransform.test_circuit_with_disconnected_components[True] _________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 2341, in test_circuit_with_disconnected_components
    res = circuit(x)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
____________________________________________________________________ TestCutCircuitTransform.test_circuit_with_trivial_wire_cut[True] _____________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 2361, in test_circuit_with_trivial_wire_cut
    res = circuit(x)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
_________________________________________________________________________ TestCutCircuitTransform.test_complicated_circuit[True] __________________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 2430, in test_complicated_circuit
    res = cut_circuit(params)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
________________________________________________________________________ TestCutCircuitTransform.test_standard_circuit[None-True] _________________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 2475, in test_standard_circuit
    res = cut_circuit()
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
______________________________________________________________________ TestCutCircuitTransform.test_standard_circuit[10000000-True] _______________________________________________________________________
Traceback (most recent call last):
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1164, in cut_circuit
    import opt_einsum  # pylint: disable=import-outside-toplevel,unused-import
ModuleNotFoundError: No module named 'opt_einsum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pennylane/tests/transforms/test_qcut.py", line 2475, in test_standard_circuit
    res = cut_circuit()
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 288, in _wrapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "/home/pennylane/pennylane/transforms/batch_transform.py", line 410, in construct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "/home/pennylane/pennylane/transforms/qcut.py", line 1170, in cut_circuit
    ) from e
ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function. This package can be installed using:
pip install opt_einsum
============================================================================================ warnings summary =============================================================================================
tests/test_finite_diff.py:40
  /home/pennylane/tests/test_finite_diff.py:40: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    (x2, y2, 0, [0], 0.01, np.array([np.array([-47.34108464, 0.0]), 0])),

pennylane/ops/qubit/non_parametric_ops.py:1770: 1 warning
drawer/test_circuit_drawer.py: 1 warning
transforms/test_commutation_dag.py: 3 warnings
transforms/test_get_unitary_matrix.py: 1 warning
transforms/test_qmc_transform.py: 9 warnings
  /home/pennylane/pennylane/ops/qubit/non_parametric_ops.py:1770: UserWarning: The control_wires keyword will be removed soon. Use wires = (control_wires, target_wire) instead. See the documentation for more information.
    category=UserWarning,

test_about.py: 134 warnings
  /home/anaconda3/envs/PL_test/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:114: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
    DeprecationWarning,

test_measurements.py::TestSample::test_sample_combination
test_measurements.py::TestSample::test_sample_output_type_in_combination
test_qubit_device.py::TestShotList::test_sample[shot_list0-shot_vector0-expected_shapes0-16]
test_qubit_device.py::TestShotList::test_sample[shot_list1-shot_vector1-expected_shapes1-27]
test_qubit_device.py::TestShotList::test_multiple_sample[shot_list0-shot_vector0-expected_shapes0-16]
test_qubit_device.py::TestShotList::test_multiple_sample[shot_list1-shot_vector1-expected_shapes1-27]
interfaces/test_batch_autograd_qnode.py::TestSample::test_sample_combination
templates/test_layer.py::TestLayer::test_layer[DynamicCircuit-1-arguments3-keywords3-gates3]
templates/test_layer.py::TestLayer::test_layer[MultiCircuit-2-arguments4-keywords4-gates4]
  /home/anaconda3/envs/PL_test/lib/python3.7/site-packages/numpy/core/fromnumeric.py:1970: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    result = asarray(a).shape

test_operation.py::TestOperationConstruction::test_error_get_parameter_shift_no_recipe
  /home/pennylane/pennylane/operation.py:1254: UserWarning: The method get_parameter_shift is deprecated. Use the methods of the gradients module for general parameter-shift rules instead.
    UserWarning,

test_optimize_shot_adapative.py::TestSingleShotGradientIntegration::test_single_array_argument_step[cost_fn1]
test_optimize_shot_adapative.py::TestSingleShotGradientIntegration::test_multiple_array_argument_step
test_optimize_shot_adapative.py::TestOptimization::test_multi_qubit_rotation
  /home/pennylane/pennylane/numpy/tensor.py:155: RuntimeWarning: invalid value encountered in true_divide
    res = super().__array_ufunc__(ufunc, method, *args, **kwargs)

test_prob.py: 20 warnings
transforms/test_decompositions.py: 108 warnings
transforms/test_get_unitary_matrix.py: 46 warnings
transforms/test_unitary_to_rot.py: 5 warnings
transforms/test_optimization/test_commute_controlled.py: 2 warnings
transforms/test_optimization/test_optimization_utils.py: 17 warnings
transforms/test_optimization/test_single_qubit_fusion.py: 3 warnings
  /home/pennylane/pennylane/transforms/get_unitary_matrix.py:107: UserWarning: get_unitary_matrix is deprecated, and will be removed in an upcoming release. For extracting matrices of operations and quantum functions, please use qml.matrix().
    UserWarning,

circuit_graph/test_circuit_graph.py: 2 warnings
fourier/test_reconstruct.py: 1 warning
gradients/test_finite_difference.py: 1 warning
interfaces/test_batch_autograd_qnode.py: 3 warnings
interfaces/test_qnode_autograd.py: 3 warnings
  /home/anaconda3/envs/PL_test/lib/python3.7/site-packages/autograd/numpy/numpy_wrapper.py:77: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    return _np.array(args, *array_args, **array_kwargs)

circuit_graph/test_qasm.py::TestQNodeQasmIntegrationTests::test_parametrized_native_qasm_gates
  /home/pennylane/tests/circuit_graph/test_qasm.py:403: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    params = np.array([0.5, [0.2, 0.1]])

circuit_graph/test_qasm.py::TestQNodeQasmIntegrationTests::test_parametrized_native_qasm_gates
  /home/pennylane/tests/circuit_graph/test_qasm.py:429: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    params = np.array([0.1, [0.3, 0.2]])

fourier/test_reconstruct.py::TestReconstructGen::test_with_classical_fun_spectrum_overcomplete[<lambda>-spectrum0]
  /home/pennylane/pennylane/fourier/reconstruct.py:167: UserWarning: The condition number of the Fourier transform matrix is very large: 470216686.7146286.
    UserWarning,

fourier/test_reconstruct.py::TestReconstruct::test_differentiability_autograd[qnode_4-params8-ids8-nums_frequency8-None-None-1]
fourier/test_reconstruct.py::TestReconstruct::test_differentiability_autograd[qnode_5-params9-ids9-nums_frequency9-None-None-5]
interfaces/test_batch_autograd_qnode.py::TestTapeExpansion::test_hamiltonian_expansion_analytic[2-default.qubit-backprop-forward]
interfaces/test_batch_autograd_qnode.py::TestTapeExpansion::test_hamiltonian_expansion_finite_shots[2-default.qubit-parameter-shift-backward]
templates/test_subroutines/test_commuting_evolution.py::TestGradients::test_differentiable_hamiltonian
  /home/anaconda3/envs/PL_test/lib/python3.7/site-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
    warnings.warn("Output seems independent of input.")

gradients/test_finite_difference.py: 12 warnings
gradients/test_parameter_shift.py: 1 warning
gradients/test_vjp.py: 1 warning
interfaces/test_batch_autograd.py: 1 warning
interfaces/test_batch_autograd_qnode.py: 5 warnings
interfaces/test_qnode_autograd.py: 5 warnings
interfaces/test_tape_autograd.py: 1 warning
tape/test_jacobian_tape.py: 3 warnings
tape/test_qubit_param_shift.py: 1 warning
tape/test_tape.py: 2 warnings
  /home/pennylane/pennylane/_qubit_device.py:241: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    results = self._asarray(results)

gradients/test_general_shift_rules.py::TestGenerateShiftRule::test_near_singular_warning
  /home/anaconda3/envs/PL_test/lib/python3.7/site-packages/_pytest/python.py:192: PytestRemovedIn8Warning: Passing None has been deprecated.
  See https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests for alternatives in common use cases.
    result = testfunction(**testargs)

interfaces/test_qnode_autograd.py: 80 warnings
tape/test_jacobian_tape.py: 1 warning
tape/test_qnode_old.py: 49 warnings
tape/test_reversible.py: 66 warnings
transforms/test_specs.py: 10 warnings
  /home/pennylane/pennylane/qnode_old.py:174: UserWarning: qml.qnode_old.QNode is deprecated, and will be removed in an upcoming release. Please use qml.QNode instead.
    UserWarning,

interfaces/test_qnode_autograd.py: 76 warnings
interfaces/test_tape_autograd.py: 22 warnings
tape/test_cv_param_shift.py: 12 warnings
tape/test_jacobian_tape.py: 2 warnings
tape/test_qnode_old.py: 30 warnings
tape/test_qubit_param_shift.py: 158 warnings
tape/test_reversible.py: 70 warnings
tape/test_tape.py: 15 warnings
transforms/test_specs.py: 9 warnings
  /home/pennylane/pennylane/tape/tape.py:1340: UserWarning: Executing tapes using tape.execute(dev) is deprecated. Please use the qml.execute([tape], dev) function instead.
    "Executing tapes using tape.execute(dev) is deprecated. "

interfaces/test_qnode_autograd.py: 44 warnings
interfaces/test_tape_autograd.py: 11 warnings
tape/test_cv_param_shift.py: 26 warnings
tape/test_jacobian_tape.py: 28 warnings
tape/test_qnode_old.py: 7 warnings
tape/test_qubit_param_shift.py: 126 warnings
tape/test_reversible.py: 49 warnings
  /home/pennylane/pennylane/tape/jacobian_tape.py:560: UserWarning: Differentiating tapes using JacobianTape.jacobian() is deprecated. Please use ta standard QuantumTape with gradient transforms from the qml.gradients module instead.
    "Differentiating tapes using JacobianTape.jacobian() is deprecated. "

interfaces/test_qnode_autograd.py::TestQNode::test_sampling[default.qubit-adjoint]
  /home/pennylane/pennylane/qnode_old.py:501: UserWarning: Requested adjoint differentiation to be computed with finite shots. Adjoint differentiation always calculated exactly.
    UserWarning,

interfaces/test_qnode_autograd.py: 8 warnings
tape/test_jacobian_tape.py: 3 warnings
tape/test_qubit_param_shift.py: 42 warnings
  /home/pennylane/pennylane/tape/jacobian_tape.py:767: UserWarning: Differentiating tapes using JacobianTape.hessian() is deprecated. Please use ta standard QuantumTape with gradient transforms from the qml.gradients module instead.
    "Differentiating tapes using JacobianTape.hessian() is deprecated. "

ops/qubit/test_sparse.py::TestSparse::test_label
  /home/anaconda3/envs/PL_test/lib/python3.7/site-packages/autoray/autoray.py:84: DeprecationWarning: scipy.shape is deprecated and will be removed in SciPy 2.0.0, use numpy.shape instead
    return get_lib_fn(backend, fn)(*args, **kwargs)

optimize/test_gradient_descent.py::TestGradientDescentOptimizer::test_update_stepsize
  /home/pennylane/tests/optimize/test_gradient_descent.py:229: UserWarning: 'update_stepsize' is deprecated. Stepsize value can be updated using the 'stepsize' attribute.
    opt.update_stepsize(eta2)

optimize/test_gradient_descent.py::TestGradientDescentOptimizer::test_private_stepsize
  /home/pennylane/tests/optimize/test_gradient_descent.py:246: UserWarning: '_stepsize' is deprecated. Please use 'stepsize' instead.
    assert opt._stepsize == eta

optimize/test_gradient_descent.py::TestGradientDescentOptimizer::test_private_stepsize
  /home/pennylane/tests/optimize/test_gradient_descent.py:254: UserWarning: '_stepsize' is deprecated. Please use 'stepsize' instead.
    opt._stepsize = eta2

tape/test_jacobian_tape.py::TestJacobian::test_non_differentiable_error
  /home/pennylane/pennylane/tape/jacobian_tape.py:581: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    params = np.array(params)

tape/test_jacobian_tape.py::TestHessian::test_non_differentiable_error
  /home/pennylane/pennylane/tape/jacobian_tape.py:783: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    params = np.array(params)

tape/test_qnode_old.py::TestTapeConstruction::test_drawing_exception
tape/test_qnode_old.py::TestDrawMethod::test_invalid_wires
tape/test_qnode_old.py::TestDrawMethod::test_tape_not_constructed
tape/test_qnode_old.py::TestDrawMethod::test_show_all_wires_error
  /home/pennylane/pennylane/qnode_old.py:819: UserWarning: The QNode.draw method has been deprecated. Please use the qml.draw(qnode)(*args) function instead.
    UserWarning,

tape/test_qnode_old.py::TestShots::test_no_shots_per_call_if_user_has_shots_qfunc_arg
  /home/pennylane/pennylane/qnode_old.py:200: UserWarning: Detected 'shots' as an argument to the given quantum function. The 'shots' argument name is reserved for overriding the number of shots taken by the device. Its use outside of this context should be avoided.
    UserWarning,

transforms/test_unitary_to_rot.py::TestQubitUnitaryDifferentiability::test_gradient_unitary_to_rot[rot_angles0-parameter-shift]
transforms/test_unitary_to_rot.py::TestQubitUnitaryDifferentiability::test_gradient_unitary_to_rot[rot_angles1-backprop]
transforms/test_unitary_to_rot.py::TestQubitUnitaryDifferentiability::test_gradient_unitary_to_rot[rot_angles2-parameter-shift]
transforms/test_unitary_to_rot.py::TestQubitUnitaryDifferentiability::test_gradient_unitary_to_rot[rot_angles3-backprop]
transforms/test_unitary_to_rot.py::TestQubitUnitaryDifferentiability::test_gradient_unitary_to_rot[rot_angles4-parameter-shift]
transforms/test_unitary_to_rot.py::TestQubitUnitaryDifferentiability::test_gradient_unitary_to_rot[rot_angles5-backprop]
  /home/anaconda3/envs/PL_test/lib/python3.7/site-packages/autograd/numpy/numpy_wrapper.py:156: ComplexWarning: Casting complex values to real discards the imaginary part
    return A.astype(dtype, order, casting, subok, copy)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================================= short test summary info =========================================================================================
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_simple_cut_circuit[None-True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circui...
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_simple_cut_circuit[10000000-True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_ci...
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_with_mid_circuit_measurement[True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_c...
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_device_wires[True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit function....
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_circuit_with_disconnected_components[True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in t...
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_circuit_with_trivial_wire_cut[True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_...
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_complicated_circuit[True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit fu...
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_standard_circuit[None-True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circuit ...
FAILED tests/transforms/test_qcut.py::TestCutCircuitTransform::test_standard_circuit[10000000-True] - ImportError: The opt_einsum package is required when use_opt_einsum is set to True in the cut_circ...
===================================================== 9 failed, 8976 passed, 1600 skipped, 22 xfailed, 4 xpassed, 1377 warnings in 404.80s (0:06:44) ======================================================
make: *** [Makefile:60: test] Error 1
```

### System information

```shell
Python 3.7.12 | packaged by conda-forge | (Oct 26 2021, 06:08:21) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pennylane as qml; qml.about()
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: PennyLane
Version: 0.22.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/anaconda3/envs/PL_test/lib/python3.7/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning
Platform info:           Linux
Python version:          3.7.12
Numpy version:           1.21.5
Scipy version:           1.7.3
Installed devices:
- default.gaussian (PennyLane-0.22.1)
- default.mixed (PennyLane-0.22.1)
- default.qubit (PennyLane-0.22.1)
- default.qubit.autograd (PennyLane-0.22.1)
- default.qubit.jax (PennyLane-0.22.1)
- default.qubit.tf (PennyLane-0.22.1)
- default.qubit.torch (PennyLane-0.22.1)
- lightning.qubit (PennyLane-Lightning-0.22.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by dominicpasquali** [comment]
Sorry for the error report- I just realized that many modules were not installed. I'll reopen if this problem persists.
