### ISSUE TITLE
[BUG] `batch_params` not raising error in some scenarios when batch dimensions don't match.

### ISSUE THREAD

**Issue by eddddddy** [PennyLaneAI/pennylane#2592]
### Expected behavior

A QNode wrapped in `qml.batch_params` should raise an error during construction if the batch dimensions of the input parameters don't match.

### Actual behavior

The error is not raised in some scenarios. In fact, the error is only raised when the batch dimension of the first parameter to the circuit is the largest of all the other batch dimensions. 

For example, the following code correctly raises an error:
```python
dev = qml.device('default.qubit', wires=1)

@qml.qnode(dev)
def circuit(x, y):
    qml.RY(x, wires=0)
    qml.RY(y, wires=0)
    return qml.state()
```
```pycon
>>> x = np.array([0, np.pi / 2, np.pi, 3 * np.pi / 2])
>>> y = np.array([0, 0, 0])
>>> qml.batch_params(circuit)(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\pennylane\pennylane\transforms\batch_transform.py", line 289, in _w
rapper
    tapes, processing_fn = self.construct(qnode.qtape, *targs, **tkwargs)
  File "C:\pennylane\pennylane\transforms\batch_transform.py", line 403, in co
nstruct
    tapes, processing_fn = self.transform_fn(tape, *args, **kwargs)
  File "C:\pennylane\pennylane\transforms\batch_params.py", line 132, in batch
_params
    raise ValueError(
ValueError: Parameter [0 0 0] has incorrect batch dimension. Expecting first dimension of length 4.
```
But simply swapping the values of `x` and `y` makes the error disappear:
```pycon
>>> y = np.array([0, np.pi / 2, np.pi, 3 * np.pi / 2])
>>> x = np.array([0, 0, 0])
>>> qml.batch_params(circuit)(x, y)
tensor([[1.00000000e+00+0.j, 0.00000000e+00+0.j],
        [7.07106781e-01+0.j, 7.07106781e-01+0.j],
        [6.12323400e-17+0.j, 1.00000000e+00+0.j]], requires_grad=True)
```
It looks like the last element in the batch is ignored in the latter scenario.

### Additional information

The issue seems to be in lines 120-135 in `batch_params.py` (in the current master):

```python
try:
    batch_dim = qml.math.shape(params[0])[0]
except IndexError:
    raise ValueError(f"Parameter {params[0]} does not contain a batch dimension.") from None

unbatched_params = [[] for i in range(batch_dim)]

for p in params:
    for i in range(batch_dim):
        try:
            unbatched_params[i].append(p[i])
        except IndexError:
            raise ValueError(
                f"Parameter {p} has incorrect batch dimension. Expecting "
                f"first dimension of length {batch_dim}."
            ) from None
```
In particular, the IndexError is only raised if `batch_dim` is greater than the batch dimension of an input parameter. Since we set `batch_dim` to be the batch dimension of the first parameter, this error is only raised when the batch dimension of the first parameter is the largest.

Instead, we should check directly whether the batch dimensions are equal, using something like (untested):
```python
for p in params:
    try:
        shape = qml.math.shape(p)[0]
    except IndexError:
        error = True 
    if  shape != batch_dim or error:
        raise ValueError(...)
```

The test file also needs to be changed to catch something like this in the future.

### System information

```shell
Name: PennyLane
Version: 0.24.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: c:\eddddddy\pennylane
Requires: numpy, scipy, networkx, retworkx, autograd, toml, appdirs, semantic-version, autoray, cachetools, pennylan
e-lightning
Required-by: PennyLane-Lightning

Platform info:           Windows-10-10.0.19042-SP0
Python version:          3.8.10
Numpy version:           1.22.3
Scipy version:           1.8.0
Installed devices:
- default.gaussian (PennyLane-0.24.0.dev0)
- default.mixed (PennyLane-0.24.0.dev0)
- default.qubit (PennyLane-0.24.0.dev0)
- default.qubit.autograd (PennyLane-0.24.0.dev0)
- default.qubit.jax (PennyLane-0.24.0.dev0)
- default.qubit.tf (PennyLane-0.24.0.dev0)
- default.qubit.torch (PennyLane-0.24.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.23.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by timmysilv** [comment]
confirmed that with `x, y` the error is "The batch sizes of the quantum script operations do not match, they include 4 and 3.", but with re-ordering as `y, x`, the error is "The batch sizes of the quantum script operations do not match, they include 3 and 4." (ie. the sizes swapped as expected). Fixed!
