### ISSUE TITLE
QubitUnitary compatiblity with TF optimizers

### ISSUE THREAD

**Issue by JoeGibbs88** [PennyLaneAI/pennylane#2604]
Is QubitUnitary incompatible with the Tensorflow optimisers? A simple example is shown below (where the optimal parameter is theta = +-pi), the standard PennyLane Optimiser runs correctly, however the tf optimiser fails with an error.
I am unsure whether there is a modification that needs to be made to the custom gate to allow for the autodiff to work correctly. It could be to do with the np array in the gate definition, but the documentation doesn't indicate what this should be changed to in this instance.

i.e. runs correctly:
```
import pennylane as qml
from pennylane import numpy as np
from numpy.random import uniform

import tensorflow as tf

def G(theta):
  U = np.array([[1, 0, 0, 0],
                [0, np.cos(theta/2), -np.sin(theta/2), 0],
                [0, np.sin(theta/2), np.cos(theta/2), 0],
                [0, 0, 0, 1]])
  return U

dev = qml.device('default.qubit', wires=2)
@qml.qnode(dev)
def circuit(theta):

  qml.PauliX(wires=0)

  qml.QubitUnitary(G(theta[0]), wires=[0,1])

  qml.PauliX(wires=1)

  return qml.probs(wires=[0,1])

def lossfn(theta):

  return 1-circuit(theta)[0]

steps = 10**2 + 1

theta = np.array([uniform(-np.pi, np.pi)], requires_grad=True)

print()
print("Random Initialization: ", lossfn(theta).numpy())
print()
print("Minimum: ", lossfn([np.pi]).numpy())
print()

opt = qml.GradientDescentOptimizer(stepsize=0.1)

steps = 100


for i in range(steps):
  theta = opt.step(lossfn, theta)

  print("Cost after step {:5d}: {: .7f}".format(i + 1, lossfn(theta)))

print("Optimized rotation angles: {}".format(theta))
```

Whereas the below using the tf.keras optimiser fails:

```
import pennylane as qml
from pennylane import numpy as np
from numpy.random import uniform

import tensorflow as tf

def G(theta):
  U = np.array([[1, 0, 0, 0],
                [0, np.cos(theta/2), -np.sin(theta/2), 0],
                [0, np.sin(theta/2), np.cos(theta/2), 0],
                [0, 0, 0, 1]])
  return U

dev = qml.device('default.qubit', wires=2)
@qml.qnode(dev, interface='tf')
def circuit(theta):

  qml.PauliX(wires=0)

  qml.QubitUnitary(G(theta[0]), wires=[0,1])

  qml.PauliX(wires=1)

  return qml.probs(wires=[0,1])

def lossfn(theta):

  return 1-circuit(theta)[0]

opt = tf.keras.optimizers.Adam(learning_rate=0.1)
steps = 10**2 + 1

theta = tf.Variable([uniform(-np.pi, np.pi)], dtype=tf.float64)

print()
print("Random Initialization: ", lossfn(theta).numpy())
print()
print("Minimum: ", lossfn([np.pi]).numpy())
print()

for i in range(1, steps):
  with tf.GradientTape() as tape:
    loss = lossfn(theta)

  gradients = tape.gradient(loss, [theta])
  opt.apply_gradients(zip(gradients, [theta]))
  print(i, lossfn(theta).numpy())
```

Error:

```
2022-05-22 22:00:25.892512: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Random Initialization:  0.578355020945559

Minimum:  0.0

Traceback (most recent call last):
  File "QU_error.py", line 46, in <module>
    opt.apply_gradients(zip(gradients, [theta]))
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/keras/optimizer_v2/optimizer_v2.py", line 633, in apply_gradients
    grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/keras/optimizer_v2/utils.py", line 73, in filter_empty_gradients
    raise ValueError(f"No gradients provided for any variable: {variable}. "
ValueError: No gradients provided for any variable: (['Variable:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'Variable:0' shape=(1,) dtype=float64, numpy=array([-1.41343768])>),).
```

**Comment by josh146** [comment]
Hey @JoeGibbs88!

The reason for your error message ("No gradients provided for any variable") is because your function `G(theta)` uses NumPy functions on TensorFlow tensors, breaking the ability for TensorFlow to backpropagate through your model.

If you re-write the function to use TensorFlow, your code above will now optimize using Keras:

```python
def G(theta):
    ct = tf.cos(theta / 2)
    st = tf.sin(theta / 2)

    indices = [[1, 1], [1, 2], [2, 1], [2, 2]]
    values = [ct, -st, st, ct]

    U = tf.eye(4, dtype=tf.float64)
    U = tf.tensor_scatter_nd_update(U, indices, values)
    return U
```

**Comment by JoeGibbs88** [comment]
Solved, thanks for the help!

**Comment by JoeGibbs88** [comment]
@josh146 Following this, how do I include complex numbers in the gate definition? e.g. (2) from https://www.nature.com/articles/s41534-019-0240-1.pdf:

```
def A(theta, phi):
  ct = tf.cos(theta / 2)
  st = tf.sin(theta / 2)

  indices = [[1, 1], [1, 2], [2, 1], [2, 2]]
  values = [ct, st*tf.exp(tf.complex(0., phi)), st*tf.exp(tf.complex(0, -phi)), -ct]
  
  U = tf.eye(4, dtype=tf.complex128)
  U = tf.tensor_scatter_nd_update(U, indices, values)
  return U
```

I'm not sure how to generate the complex number in the exponential because I keep getting the below error:

```
File "first_tf.py", line 26, in A
    values = [ct, st*tf.exp(tf.complex(0., phi)), st*tf.exp(tf.complex(0, -phi)), -ct]
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/anaconda3/envs/qml-env/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 742, in complex
    f"The `real` and `imag` components have incorrect types: "
TypeError: The `real` and `imag` components have incorrect types: float32 float64. They must be consistent, and one of [tf.float32, tf.float64]
```
