### ISSUE TITLE
[BUG] AllSinglesDoubles cannot be JIT compiled with JAX

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/pennylane#3226]
### Expected behavior

The example use of template AllSingleDoubles should be JIT compiled with JAX.

### Actual behavior

The example use of template AllSingleDoubles cannot be JIT compiled with JAX.

### Source code

```shell
import pennylane as qml
import jax
import numpy as np

electrons = 2
qubits = 4

# Define the HF state
hf_state = qml.qchem.hf_state(electrons, qubits)

# Generate all single and double excitations
singles, doubles = qml.qchem.excitations(electrons, qubits)

# Define the device
dev = qml.device('default.qubit', wires=qubits)

wires = range(qubits)

@qml.qnode(dev)
def circuit(weights, hf_state, singles, doubles):
    qml.templates.AllSinglesDoubles(weights, wires, hf_state, singles, doubles)
    return qml.expval(qml.PauliZ(0))

# Evaluate the QNode for a given set of parameters
params = np.random.normal(0, np.pi, len(singles) + len(doubles))
jitted_circuit = jax.jit(circuit)
jitted_circuit(params, hf_state, singles=singles, doubles=doubles)
```

### Tracebacks

```shell
--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/erick/bug_report_01.py", line 30, in <module>
    jitted_circuit(params, hf_state, singles=singles, doubles=doubles)
  File "/home/erick/.local/lib/python3.10/site-packages/pennylane/qnode.py", line 611, in __call__
    self.construct(args, kwargs)
  File "/home/erick/.local/lib/python3.10/site-packages/pennylane/qnode.py", line 526, in construct
    self._qfunc_output = self.func(*args, **kwargs)
  File "/home/erick/bug_report_01.py", line 24, in circuit
    qml.templates.AllSinglesDoubles(weights, wires, hf_state, singles, doubles)
  File "/home/erick/.local/lib/python3.10/site-packages/pennylane/templates/subroutines/all_singles_doubles.py", line 147, in __init__
    "hf_state": qml.math.toarray(hf_state),
  File "/home/erick/.local/lib/python3.10/site-packages/autoray/autoray.py", line 85, in do
    return get_lib_fn(backend, fn)(*args, **kwargs)
  File "/home/erick/.local/lib/python3.10/site-packages/pennylane/math/single_dispatch.py", line 639, in _to_numpy_jax
    raise ValueError(
ValueError: Converting a JAX array to a NumPy array not supported when using the JAX JIT.
```

### System information

```shell
Name: PennyLane
Version: 0.26.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author:
Author-email:
License: Apache License 2.0
Location: /home/erick/.local/lib/python3.10/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Python version:          3.10.8
Numpy version:           1.23.2
Scipy version:           1.9.0
Installed devices:
- default.gaussian (PennyLane-0.26.0)
- default.mixed (PennyLane-0.26.0)
- default.qubit (PennyLane-0.26.0)
- default.qubit.autograd (PennyLane-0.26.0)
- default.qubit.jax (PennyLane-0.26.0)
- default.qubit.tf (PennyLane-0.26.0)
- default.qubit.torch (PennyLane-0.26.0)
- default.qutrit (PennyLane-0.26.0)
- lightning.qubit (PennyLane-Lightning-0.26.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by erick-xanadu** [comment]
I see, thanks @eddddddy! You can close this ticket then. :)
