### ISSUE TITLE
[BUG] `Sample` does not work with jitting when a subset of wires are used

### ISSUE THREAD

**Issue by mudit2812** [PennyLaneAI/pennylane#3904]
### Expected behavior

`qml.sample` works without errors when a circuit with parameters is jitted and a subset of the circuit wires are specified in the call to `qml.sample`.

### Actual behavior

An exception is raised due to a mismatch between exepected and actual output shape. Note that when the circuit does not have any parameters, no error is raised and the output is correct.

### Source code

```shell
>>> import pennylane as qml
>>> import jax
>>> import jax.numpy as jnp
>>> jax.config.update("jax_enable_x64", True)
>>> dev = qml.device("default.qubit", wires=3, shots=5)
>>> @qml.qnode(dev, interface="jax")
... def circuit(p):
...     qml.broadcast(qml.Hadamard, pattern="single", wires=dev.wires)
...     qml.RX(p, wires=0)
...     return qml.sample(wires=0)
... 
>>> jitted_qnode = jax.jit(circuit)
>>> jitted_qnode(jnp.array(0.123))
```

### Tracebacks

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 163, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/api.py", line 695, in cache_miss
    out_flat = call_bind_continuation(execute(*args_flat))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 2108, in __call__
    out_bufs = self.xla_executable.execute_sharded_on_local_devices(
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Generated function failed: CpuCallback error: RuntimeError: Incorrect output shape for return value 0: Expected: (1, 5, 3), Actual: (1, 5, 1)

At:
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/interpreters/mlir.py(1796): _wrapped_callback
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py(2108): __call__
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/profiler.py(314): wrapper
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/api.py(695): cache_miss
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/traceback_util.py(163): reraise_with_filtered_traceback
  <stdin>(1): <module>

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Generated function failed: CpuCallback error: RuntimeError: Incorrect output shape for return value 0: Expected: (1, 5, 3), Actual: (1, 5, 1)

At:
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/interpreters/mlir.py(1796): _wrapped_callback
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py(2108): __call__
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/profiler.py(314): wrapper
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/api.py(695): cache_miss
  /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages/jax/_src/traceback_util.py(163): reraise_with_filtered_traceback
  <stdin>(1): <module>
```

### System information

```shell
Name: PennyLane
Version: 0.30.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /opt/homebrew/Caskroom/miniforge/base/envs/qml/lib/python3.9/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Cirq, PennyLane-Lightning, PennyLane-qiskit

Platform info:           macOS-13.2.1-arm64-arm-64bit
Python version:          3.9.15
Numpy version:           1.23.5
Scipy version:           1.10.0
Installed devices:
- default.gaussian (PennyLane-0.30.0.dev0)
- default.mixed (PennyLane-0.30.0.dev0)
- default.qubit (PennyLane-0.30.0.dev0)
- default.qubit.autograd (PennyLane-0.30.0.dev0)
- default.qubit.jax (PennyLane-0.30.0.dev0)
- default.qubit.tf (PennyLane-0.30.0.dev0)
- default.qubit.torch (PennyLane-0.30.0.dev0)
- default.qutrit (PennyLane-0.30.0.dev0)
- null.qubit (PennyLane-0.30.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.28.1)
- cirq.mixedsimulator (PennyLane-Cirq-0.28.0)
- cirq.pasqal (PennyLane-Cirq-0.28.0)
- cirq.qsim (PennyLane-Cirq-0.28.0)
- cirq.qsimh (PennyLane-Cirq-0.28.0)
- cirq.simulator (PennyLane-Cirq-0.28.0)
- qiskit.aer (PennyLane-qiskit-0.28.0)
- qiskit.basicaer (PennyLane-qiskit-0.28.0)
- qiskit.ibmq (PennyLane-qiskit-0.28.0)
- qiskit.ibmq.circuit_runner (PennyLane-qiskit-0.28.0)
- qiskit.ibmq.sampler (PennyLane-qiskit-0.28.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
We probably just need to change `SampleMP.shape`.
