### ISSUE TITLE
[BUG] Controlled GlobalPhase assumes non-0 control wire

### ISSUE THREAD

**Issue by timmysilv** [PennyLaneAI/pennylane#4578]
### Expected behavior

I expect the controlled-GlobalPhase to apply to the state as expected, without the generator failing to be created.

### Actual behavior

The generator is not correctly constructed and the circuit fails.

### Additional information

It occurs because of [Controlled.generator()](https://github.com/PennyLaneAI/pennylane/blob/39e657784932c2fbcf70f848b250f0f8bf2c4c94/pennylane/ops/op_math/controlled.py#L526-L528). In the linked case, we have `sub_gen` equal to `qml.Hamiltonian([-1], [qml.Identity(0)])`, and `proj_tensor` equal to `qml.operation.Tensor(qml.Projector([1], 0))`. Those fail to be matmul'd together because they are observables (cast to Hamiltonians if needed) acting on the same wire. Interestingly, if you change `wire` to `1` in my linked example, it passes because `qml.GlobalPhase.generator()` always returns `(-1) [I0]` regardless of actual wires available (as a default because `Identity` needs wires). To avoid the issue of Identity needing wires, we could just use the new arithmetic operators (`qml.prod`, `qml.s_prod`), as they don't enforce the unique-wires requirement. Unfortunately, PennyLane's generator-handling code assumes they are of type `Hamiltonian` across the code-base. If this can wait, I would propose updating PL's generator code (including this function) to use the new arithmetic operators, and this problem will resolve itself.

Note that this occurs with all interfaces afaik, but only with trainable parameters and `diff_method="adjoint"`

### Source code

```shell
import torch

wire = 0
dev = qml.device("default.qubit", wires=[wire])

@qml.qnode(dev, diff_method="adjoint")
def circuit(x):
    qml.Hadamard(wire)
    qml.ctrl(qml.GlobalPhase(x), wire)
    qml.Hadamard(wire)
    return qml.expval(qml.PauliZ(wire))

phi = torch.tensor(2.1, requires_grad=True)
circuit(phi)
```

### Tracebacks

```shell
Traceback (most recent call last):
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/transforms/op_transforms.py", line 264, in fn
    return self.tape_fn(obj.expand(), *args, **kwargs)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/operation.py", line 1425, in expand
    raise DecompositionUndefinedError
pennylane.operation.DecompositionUndefinedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/qnode.py", line 963, in __call__
    res = qml.execute(
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/interfaces/execution.py", line 735, in execute
    results = ml_boundary_execute(
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/interfaces/torch.py", line 314, in execute
    return ExecuteTapes.apply(kwargs, *parameters)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/interfaces/torch.py", line 45, in new_apply
    flat_out = orig_apply(out_struct_holder, *inp)
  File "/Users/matthews/.pyenv/versions/pl/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/interfaces/torch.py", line 49, in new_forward
    out = orig_fw(ctx, *inp)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/interfaces/torch.py", line 145, in forward
    res, ctx.jacs = ctx.execute_fn(ctx.tapes, **ctx.gradient_kwargs)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/interfaces/execution.py", line 686, in device_execute_and_gradients
    return set_shots(device, override_shots)(device.execute_and_gradients)(
  File "/Users/matthews/.pyenv/versions/3.9.13/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/_device.py", line 574, in execute_and_gradients
    jacs.append(gradient_method(circuit, **kwargs))
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/_qubit_device.py", line 1653, in adjoint_jacobian
    d_op_matrix = operation_derivative(op)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/operation.py", line 2854, in operation_derivative
    qml.generator(operation, format="observable"), wire_order=operation.wires
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/transforms/op_transforms.py", line 213, in __call__
    return self._create_wrapper(obj, *targs, **tkwargs)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/transforms/op_transforms.py", line 410, in _create_wrapper
    wrapper = self.fn(obj, *targs, **tkwargs)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/transforms/op_transforms.py", line 273, in fn
    raise e1 from e
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/transforms/op_transforms.py", line 258, in fn
    return self._fn(obj, *args, **kwargs)
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/ops/functions/generator.py", line 174, in generator
    gen = op.generator()
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/ops/op_math/controlled.py", line 528, in generator
    return 1.0 * proj_tensor @ sub_gen
  File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/ops/qubit/hamiltonian.py", line 637, in __matmul__
    raise ValueError(
ValueError: Hamiltonians can only be multiplied together if they act on different sets of wires
```

### System information

```shell
pl dev
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by astralcai** [comment]
Fixed
