### ISSUE TITLE
[BUG] Shot vectors with jitting don't work for parametrized `QNode`s

### ISSUE THREAD

**Issue by mudit2812** [PennyLaneAI/pennylane#4689]
### Expected behavior

Shot vectors work with jitting all the time.

### Actual behavior

If a qnode accepts parameters, jitting it with a shot vector raises an error. This happens when shots are set during device creation as well as when shots are specified on the qnode. The errors do not occur if the qnode doesn't have any parameters, even if a parametrized operation inside a qnode uses values from an outer context as its parameters.

### Source code

```shell
>>> dev = qml.device("default.qubit")
>>> @qml.qnode(dev, interface="jax")
... def f(p):
...     qml.RX(p, 0)
...     qml.CNOT([0, 1])
...     return qml.expval(qml.PauliZ(0))
... 
>>> f_jitted = jax.jit(f, static_argnames=["shots"])
```

### Tracebacks

```shell
>>> f_jitted(jax.numpy.array(np.pi / 2), shots=(10, 10))
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mudit.pandey/repos/pennylane/pennylane/qnode.py", line 1010, in __call__
    res = qml.execute(
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/execution.py", line 736, in execute
    results = ml_boundary_execute(
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/jax_jit.py", line 278, in execute
    return _execute_bwd(
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/jax_jit.py", line 363, in _execute_bwd
    return execute_wrapper(params)
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/jax_jit.py", line 324, in execute_wrapper
    return jax.pure_callback(wrapper, shape_dtype_structs, inner_params, vectorized=True)
  File "/Users/mudit.pandey/.pyenv/versions/pennylane/lib/python3.10/site-packages/jax/_src/callback.py", line 334, in pure_callback_api
    return pure_callback(
  File "/Users/mudit.pandey/.pyenv/versions/pennylane/lib/python3.10/site-packages/jax/_src/callback.py", line 261, in pure_callback
    tree_util.tree_map(_check_shape_dtype, result_shape_dtypes)
  File "/Users/mudit.pandey/.pyenv/versions/pennylane/lib/python3.10/site-packages/jax/_src/callback.py", line 216, in _check_shape_dtype
    raise ValueError(
ValueError: Cannot return 64-bit values when `jax_enable_x64` is disabled
>>> jax.config.update("jax_enable_x64", True)
>>> f_jitted(jax.numpy.array(np.pi / 2), shots=(10, 10))
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mudit.pandey/repos/pennylane/pennylane/qnode.py", line 1010, in __call__
    res = qml.execute(
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/execution.py", line 736, in execute
    results = ml_boundary_execute(
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/jax_jit.py", line 278, in execute
    return _execute_bwd(
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/jax_jit.py", line 363, in _execute_bwd
    return execute_wrapper(params)
  File "/Users/mudit.pandey/repos/pennylane/pennylane/interfaces/jax_jit.py", line 324, in execute_wrapper
    return jax.pure_callback(wrapper, shape_dtype_structs, inner_params, vectorized=True)
  File "/Users/mudit.pandey/.pyenv/versions/pennylane/lib/python3.10/site-packages/jax/_src/callback.py", line 334, in pure_callback_api
    return pure_callback(
  File "/Users/mudit.pandey/.pyenv/versions/pennylane/lib/python3.10/site-packages/jax/_src/callback.py", line 262, in pure_callback
    result_avals = tree_util.tree_map(
  File "/Users/mudit.pandey/.pyenv/versions/pennylane/lib/python3.10/site-packages/jax/_src/callback.py", line 263, in <lambda>
    lambda x: core.ShapedArray(x.shape, x.dtype), result_shape_dtypes)
TypeError: Shapes must be 1D sequences of concrete values of integer type, got ((), ()).
```

### System information

```shell
Name: PennyLane
Version: 0.33.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /Users/mudit.pandey/repos/pennylane
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing_extensions
Required-by: PennyLane-Lightning

Platform info:           macOS-13.6-arm64-arm-64bit
Python version:          3.10.12
Numpy version:           1.23.5
Scipy version:           1.11.1
Installed devices:
- default.gaussian (PennyLane-0.33.0.dev0)
- default.mixed (PennyLane-0.33.0.dev0)
- default.qubit (PennyLane-0.33.0.dev0)
- default.qubit.autograd (PennyLane-0.33.0.dev0)
- default.qubit.jax (PennyLane-0.33.0.dev0)
- default.qubit.legacy (PennyLane-0.33.0.dev0)
- default.qubit.tf (PennyLane-0.33.0.dev0)
- default.qubit.torch (PennyLane-0.33.0.dev0)
- default.qutrit (PennyLane-0.33.0.dev0)
- null.qubit (PennyLane-0.33.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.32.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
Additional information:

specifying a shot vector on the device also doesn't work.

**Comment by albi3ro** [comment]
Fixed just this case locally by changing `pennylane/interfaces/jax_jit.py:_create_shape_dtype_struct`

```
def _create_shape_dtype_struct(tape: "qml.tape.QuantumScript", device: "qml.Device"):
    """Auxiliary function for creating the shape and dtype object structure
    given a tape."""

    shape = tape.shape(device)
    if len(shape) == 1:
        tape_dtype = _numeric_type_to_dtype(tape.numeric_type)
        return jax.ShapeDtypeStruct(tuple(shape), tape_dtype)

    if tape.shots.has_partitioned_shots:
        tape_dtype = _numeric_type_to_dtype(tape.numeric_type)
        return tuple(jax.ShapeDtypeStruct(tuple(s), tape_dtype) for s in shape)

    tape_dtype = tuple(_numeric_type_to_dtype(elem) for elem in tape.numeric_type)
    return tuple(jax.ShapeDtypeStruct(tuple(s), d) for s, d in zip(shape, tape_dtype))
```

But we will also need to include logical branches for multiple measurements and shot vectors.
