### ISSUE TITLE
[BUG] MultiControlledX decomposition

### ISSUE THREAD

**Issue by vincentmr** [PennyLaneAI/pennylane#4923]
### Expected behavior

I expect the following to produce the decomposition for all qubit counts
```
import pennylane as qml

for num_qubits in range(2, 20):
    wires = list(range(num_qubits))
    op = qml.MultiControlledX(wires=wires)
    print(op.compute_decomposition(wires, work_wires=[num_qubits])) # fails at num_qubits >= 5
```

### Actual behavior

It fails for `num_qubits` greater than 5.
```
Traceback (most recent call last):
  File "/tmp/bug.py", line 6, in <module>
    print(op.compute_decomposition(wires, work_wires=[num_qubits])) # fails at num_qubits >= 5
  File "/tmp/venv/lib/python3.10/site-packages/pennylane/ops/qubit/non_parametric_ops.py", line 2250, in compute_decomposition
    decomp = MultiControlledX._decomposition_with_one_worker(
  File "/tmp/venv/lib/python3.10/site-packages/pennylane/ops/qubit/non_parametric_ops.py", line 2315, in _decomposition_with_one_worker
    wires=first_part + work_wire,
TypeError: can only concatenate list (not "int") to list
```

### Additional information

The following works
```
import pennylane as qml

for num_qubits in range(2, 20):
    wires = list(range(num_qubits))
    op = qml.MultiControlledX(wires=wires)
    # print(op.compute_decomposition(wires, work_wires=[num_qubits])) # fails at num_qubits >= 5
    print(op.compute_decomposition(wires, work_wires=list(range(num_qubits, 2*num_qubits-3))))
```
as it hits `_decomposition_with_many_workers`, I reckon. 

### System information

```shell
Name: PennyLane
Version: 0.33.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /tmp/venv/lib/python3.10/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane-Lightning

Platform info:           Linux-5.15.0-88-generic-x86_64-with-glibc2.31
Python version:          3.10.13
Numpy version:           1.26.2
Scipy version:           1.11.4
Installed devices:
- default.gaussian (PennyLane-0.33.1)
- default.mixed (PennyLane-0.33.1)
- default.qubit (PennyLane-0.33.1)
- default.qubit.autograd (PennyLane-0.33.1)
- default.qubit.jax (PennyLane-0.33.1)
- default.qubit.legacy (PennyLane-0.33.1)
- default.qubit.tf (PennyLane-0.33.1)
- default.qubit.torch (PennyLane-0.33.1)
- default.qutrit (PennyLane-0.33.1)
- null.qubit (PennyLane-0.33.1)
- lightning.qubit (PennyLane-Lightning-0.33.1)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by vincentmr** [comment]
As per discussion, this may be due to a missing conversion prior to calling `compute_decomposition`. The following works fine
```
import pennylane as qml

for num_qubits in range(2, 20):
    wires = list(range(num_qubits))
    op = qml.MultiControlledX(wires=wires, work_wires=[num_qubits])
    print(op.decomposition())
```

**Comment by mudit2812** [comment]
Yep, that's exactly why. The line that raises an error tries to add a list with a scalar when you directly use `compute_decomposition`. When `op.decomposition` is used, the control wires are wrapped in a `Wires` object, which supports addition with scalars, hence why `op.decomposition` works as expected.
