### ISSUE TITLE
[BUG] Error Installing pennylane-lightning[gpu] in conda environment

### ISSUE THREAD

**Issue by gmseabra** [PennyLaneAI/pennylane#4984]
### Expected behavior

I'm trying to install the lightning[gpu] in my conda env. However, I'm getting this error related to the installation.  Thanks!

Expected behavior: Pennylane lightning[gpu] installs correctly.

### Actual behavior

```
(pennylane) [ ~]$ pip install pennylane-lightning[gpu]
Requirement already satisfied: pennylane-lightning[gpu] in ./.conda/envs/pennylane/lib/python3.12/site-packages (0.33.1)
Requirement already satisfied: pennylane>=0.32 in ./.conda/envs/pennylane/lib/python3.12/site-packages (from pennylane-lightning[gpu]) (0.33.1)
Collecting pennylane-lightning-gpu (from pennylane-lightning[gpu])
  Using cached PennyLane_Lightning_GPU-0.33.1.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-p2ffx7bs/pennylane-lightning-gpu_e2dcf8e305fe40ea85a3445a4b992fdf/setup.py", line 168, in <module>
          with open(os.path.join("pennylane_lightning", "core", "_version.py"), encoding="utf-8") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'pennylane_lightning/core/_version.py'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Additional information

Here's the contents of my conda env:

```
(pennylane) [ ~]$ conda list
# packages in environment at /home/seabra/.conda/envs/pennylane:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
autograd                  1.6.2                    pypi_0    pypi
autoray                   0.6.7                    pypi_0    pypi
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
comm                      0.2.1              pyhd8ed1ab_0    conda-forge
debugpy                   1.8.0           py312h30efb56_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
future                    0.18.3                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
ipykernel                 6.28.0             pyhd33586a_0    conda-forge
ipython                   8.19.0             pyh707e725_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.6.1           py312h7900ff3_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
networkx                  3.2.1                    pypi_0    pypi
numpy                     1.26.3                   pypi_0    pypi
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pennylane                 0.33.1                   pypi_0    pypi
pennylane-lightning       0.33.1                   pypi_0    pypi
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
psutil                    5.9.7           py312h98912ed_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
python                    3.12.1          hab00c5b_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pyzmq                     25.1.2          py312h886d080_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
rustworkx                 0.13.2                   pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml                      0.10.2                   pypi_0    pypi
tornado                   6.3.3           py312h98912ed_1    conda-forge
traitlets                 5.14.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
urllib3                   2.1.0                    pypi_0    pypi
wcwidth                   0.2.12             pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zeromq                    4.3.5                h59595ed_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge

```

### System information

```shell
(pennylane) [ ~]$ ipython
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pennylane as qml

In [2]: qml.about()
Name: PennyLane
Version: 0.33.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author:
Author-email:
License: Apache License 2.0
Location: /home/seabra/.conda/envs/pennylane/lib/python3.12/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane-Lightning

Platform info:           Linux-4.18.0-477.27.1.el8_8.x86_64-x86_64-with-glibc2.28
Python version:          3.12.1
Numpy version:           1.26.3
Scipy version:           1.11.4
Installed devices:
- default.gaussian (PennyLane-0.33.1)
- default.mixed (PennyLane-0.33.1)
- default.qubit (PennyLane-0.33.1)
- default.qubit.autograd (PennyLane-0.33.1)
- default.qubit.jax (PennyLane-0.33.1)
- default.qubit.legacy (PennyLane-0.33.1)
- default.qubit.tf (PennyLane-0.33.1)
- default.qubit.torch (PennyLane-0.33.1)
- default.qutrit (PennyLane-0.33.1)
- null.qubit (PennyLane-0.33.1)
- lightning.qubit (PennyLane-Lightning-0.33.1)
```
```


### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
Thanks for opening this issue @gmseabra .

I've attached a PDF with some instructions that may help. 

[PennyLane installation instructions 2024.pdf](https://github.com/PennyLaneAI/pennylane/files/13846753/PennyLane.installation.instructions.2024.pdf)

I'd also recommend posting in the [forum](https://discuss.pennylane.ai).

Please note that lightning does not yet have Python 3.12 wheels, but they should be getting released on Monday.

**Comment by mlxd** [comment]
Hi @gmseabra just to make a quick note here. It isn't recommended to directly mix conda environments and pip-installed packages, due to the different disitribution methods. If you create a Python virtualenv from your conda-provided Python (i.e `python -m venv my_env && source my_env/bin/activate`) this should help alleviate the above issue, now that we have pushed out the Python 3.12 packages.

However, if you prefer to go fully through conda, you can directly install the lightning.gpu package through our conda-forge provided package here: https://anaconda.org/conda-forge/pennylane-lightning-gpu

Feel free to let us know if this works for you.

**Comment by albi3ro** [comment]
@gmseabra Have you have any progress?

If you do not have any further questions, we will close this issue next week.

**Comment by gmseabra** [comment]
Yes, it is working now:

dev = qml.device("lightning.gpu", wires=qubits)
print(dev)


Lightning GPU PennyLane plugin
Short name: lightning.gpu
Package: pennylane_lightning
Plugin version: 0.34.0
Author: Xanadu Inc.
Wires: 6
Shots: None


Thanks!

--
Gustavo Seabra
Research Associate Professor
Center for Natural Products, Drug Discovery, and Development (CNPD3)
Department of Medicinal Chemistry
College of Pharmacy
University of Florida, Gainesville, FL, USA
________________________________

**Comment by albi3ro** [comment]
Thanks for the update 🎉
