### ISSUE TITLE
[BUG]Pennylane Snapshot does not support the keyword argument "measurement"

### ISSUE THREAD

**Issue by pratibharhegde** [PennyLaneAI/pennylane#5404]
### Expected behavior

As per the documentation, qml.Snapshot(measurement=qml.expval(qml.PauliZ(0))) in the circuit is supposed to return the expectation value of the state. 

### Actual behavior

The function does not seem to take the keyword argument meausrement.

### Source code

```shell
import pennylane as qml


dev = qml.device("default.qubit", wires=2)

@qml.qnode(dev, interface=None)
def circuit():
    qml.Snapshot(measurement=qml.expval(qml.PauliZ(0)))
    qml.Hadamard(wires=0)
    qml.Snapshot("very_important_state")
    qml.CNOT(wires=[0, 1])
    qml.Snapshot()
    return qml.expval(qml.X(0))


qml.snapshots(circuit)()
```

### Tracebacks

```shell
Traceback (most recent call last):
  File "C:/Users/hedge/AppData/Roaming/JetBrains/PyCharmEdu2022.1/scratches/scratch.py", line 17, in <module>
    qml.snapshots(circuit)()
  File "C:\Users\hedge\PycharmProjects\pennylane\venv\lib\site-packages\pennylane\debugging.py", line 96, in get_snapshots
    results = qnode(*args, **kwargs)
  File "C:\Users\hedge\PycharmProjects\pennylane\venv\lib\site-packages\pennylane\qnode.py", line 974, in __call__
    self.construct(args, kwargs)
  File "C:\Users\hedge\PycharmProjects\pennylane\venv\lib\site-packages\pennylane\qnode.py", line 872, in construct
    self._tape = make_qscript(self.func, shots)(*args, **kwargs)
  File "C:\Users\hedge\PycharmProjects\pennylane\venv\lib\site-packages\pennylane\tape\qscript.py", line 1531, in wrapper
    result = fn(*args, **kwargs)
  File "C:/Users/hedge/AppData/Roaming/JetBrains/PyCharmEdu2022.1/scratches/scratch.py", line 9, in circuit
    qml.Snapshot(measurement=qml.expval(qml.PauliZ(0)))
TypeError: __init__() got an unexpected keyword argument 'measurement'
```

### System information

```shell
Name: PennyLane
Version: 0.32.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: c:\users\hedge\pycharmprojects\pennylane\venv\lib\site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane-Lightning, PennyLane-qiskit

Platform info:           Windows-10-10.0.22621-SP0
Python version:          3.8.2
Numpy version:           1.23.5
Scipy version:           1.10.1
Installed devices:
- qiskit.aer (PennyLane-qiskit-0.33.1)
- qiskit.basicaer (PennyLane-qiskit-0.33.1)
- qiskit.ibmq (PennyLane-qiskit-0.33.1)
- qiskit.ibmq.circuit_runner (PennyLane-qiskit-0.33.1)
- qiskit.ibmq.sampler (PennyLane-qiskit-0.33.1)
- qiskit.remote (PennyLane-qiskit-0.33.1)
- default.gaussian (PennyLane-0.32.0)
- default.mixed (PennyLane-0.32.0)
- default.qubit (PennyLane-0.32.0)
- default.qubit.autograd (PennyLane-0.32.0)
- default.qubit.jax (PennyLane-0.32.0)
- default.qubit.tf (PennyLane-0.32.0)
- default.qubit.torch (PennyLane-0.32.0)
- default.qutrit (PennyLane-0.32.0)
- null.qubit (PennyLane-0.32.0)
- lightning.qubit (PennyLane-Lightning-0.32.0)
None
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
Thanks for opening this issue. 

Snapshot support for arbitrary measurements was added in PennyLane v0.34:

https://github.com/PennyLaneAI/pennylane/blob/78abf2b935ea3545f4e540d1da4b080a511b8a73/doc/releases/changelog-0.34.0.md?plain=1#L374

If you wish to use this feature, I would recommend updating your pennylane version with:

```
pip install pennylane --upgrade
```

Hope that fixes things for you :)

**Comment by pratibharhegde** [comment]
Ah, That is correct. It is working now. Thank you!
