### ISSUE TITLE
[BUG] qml.shadows.shadow_expval raises an exception

### ISSUE THREAD

**Issue by Scinawa** [PennyLaneAI/pennylane#6087]
### Expected behavior

I am running the example of [shadow_expval](https://docs.pennylane.ai/en/stable/code/api/pennylane.shadows.shadow_expval.html#pennylane.shadows.shadow_expval)

As per documentation, the actual behavior should be:

```
>>> x = np.array(1.2)
>>> circuit(x)
[array(0.3528)]
>>> qml.grad(circuit)(x)
-0.9323999999999998
```

### Actual behavior

```
python3 example.py
Traceback (most recent call last):
  File "/Users/ale/workspace/QASMoleS/example.py", line 51, in <module>
    @partial(qml.shadows.shadow_expval, H, k=1)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ale/workspace/QASMoleS/.venv-python/lib/python3.11/site-packages/pennylane/transforms/core/transform_dispatcher.py", line 142, in __call__
    raise TransformError(
pennylane.transforms.core.transform_dispatcher.TransformError: Decorating a QNode with @transform_fn(**transform_kwargs) has been removed. Please decorate with @functools.partial(transform_fn, **transform_kwargs) instead, or call the transform directly using qnode = transform_fn(qnode, **transform_kwargs). Visit the deprecations page for more details: https://docs.pennylane.ai/en/stable/development/deprecations.html#completed-deprecation-cycles
```

### Source code

```shell
H = qml.Z(0) @ qml.Z(1)
dev = qml.device("default.qubit", wires=2, shots=10000)

@partial(qml.shadows.shadow_expval, H, k=1)
@qml.qnode(dev)
def circuit(x):
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    qml.RX(x, wires=0)
    return qml.classical_shadow(wires=[0, 1])



x = np.array(1.2)
print(circuit(x))
```

### System information

```shell
>>> import pennylane as qml; qml.about()
Name: PennyLane
Version: 0.37.0
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /Users/scinawa/workspace/QASMoleS/.venv-python/lib/python3.11/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, packaging, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane_Lightning

Platform info:           macOS-14.6.1-arm64-arm-64bit
Python version:          3.11.5
Numpy version:           1.26.4
Scipy version:           1.13.1
Installed devices:
- lightning.qubit (PennyLane_Lightning-0.37.0)
- default.clifford (PennyLane-0.37.0)
- default.gaussian (PennyLane-0.37.0)
- default.mixed (PennyLane-0.37.0)
- default.qubit (PennyLane-0.37.0)
- default.qubit.autograd (PennyLane-0.37.0)
- default.qubit.jax (PennyLane-0.37.0)
- default.qubit.legacy (PennyLane-0.37.0)
- default.qubit.tf (PennyLane-0.37.0)
- default.qubit.torch (PennyLane-0.37.0)
- default.qutrit (PennyLane-0.37.0)
- default.qutrit.mixed (PennyLane-0.37.0)
- default.tensor (PennyLane-0.37.0)
- null.qubit (PennyLane-0.37.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
Thanks for opening this issue @Scinawa. We'll update the docstring shortly.

The correct syntax would be:
```
H = qml.Z(0) @ qml.Z(1)
dev = qml.device("default.qubit", wires=2, shots=10000)

@partial(qml.shadows.shadow_expval, H=H, k=1)
@qml.qnode(dev)
def circuit(x):
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    qml.RX(x, wires=0)
    return qml.classical_shadow(wires=[0, 1])
```
or:
```
@qml.qnode(dev)
def circuit(x):
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    qml.RX(x, wires=0)
    return qml.classical_shadow(wires=[0, 1])

circuit = qml.shadows.shadow_expval(circuit, H, k=1)
```

Now that you can also directly return a `qml.shadow_expval(H, k=1)` as a measurement process: https://docs.pennylane.ai/en/stable/code/api/pennylane.shadow_expval.html

**Comment by Scinawa** [comment]
Thanks!
